### ISSUE TITLE
[v4.1]: Shadow on parent causes variables to lose their value.

### ISSUE THREAD

**Issue by Viraj-10** [nativewind/nativewind#1120]
**Describe the bug**
When using variables in native, if the parent component has a shadow className, the child component's variable value becomes undefined. 

**Reproduction**
```jsx
import './global.css';
import { Text, View } from 'react-native';
import { vars } from 'nativewind';

const config = {
  light: vars({ '--brand-color': 'red' }),
  dark: vars({ '--brand-color': 'blue' }),
};
export default function App() {
  return (
    <View
      style={[
        config['light'],
        {
          flex: 1,
          height: '100%',
          width: '100%',
          justifyContent: 'center',
          alignItems: 'center',
          gap: 10,
        },
      ]}>
      <View className="shadow">
        <View className="h-7 w-7 border-2 border-red-500 bg-[--brand-color]"></View>
      </View>
      <Text>with Shadow</Text>
      <View>
        <View className="h-7 w-7 border-2 border-red-500 bg-[--brand-color]" />
      </View>
      <Text>without Shadow</Text>
    </View>
  );
}

```
[GitHub repo](https://github.com/Viraj-10/shadow-nativewind-v4-issue).

**Comment by Viraj-10** [comment]
<img width="276" alt="Screenshot 2024-10-08 at 7 23 59 PM" src="https://github.com/user-attachments/assets/6b3eb79c-2522-449a-b2a2-e9a37958ca77">

**Comment by marklawlor** [comment]
Fixed in `4.1.12`

**Comment by Viraj-10** [comment]
Hey @marklawlor, Thanks for fixing this bug. 
After updating to `v4.1.12` we have encountered one more unusual bug with text and variables.
Here is a minimal reproduction. I have attached recording of simulator as well. 

```
import './global.css';
import { Pressable, Text, View } from 'react-native';
import { vars } from 'nativewind';
import { useState } from 'react';

const config = {
  light: vars({ '--brand-color': 'red' }),
  dark: vars({ '--brand-color': 'blue' }),
};
export default function App() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <View
      style={[
        config['light'],
        {
          flex: 1,
          height: '100%',
          width: '100%',
          justifyContent: 'center',
          alignItems: 'center',
          gap: 10,
        },
      ]}>
      <Pressable
        className="rounded-lg bg-gray-700 p-5"
        onPress={() => {
          setIsOpen((prev) => !prev);
        }}>
        <Text className="text-white">Toggle Text</Text>
      </Pressable>
      {isOpen && (
        <Text className="text-base text-[--brand-color]">
          Text with Variable color and text-base
        </Text>
      )}
    </View>
  );
}

```
https://github.com/user-attachments/assets/7e8e3af5-b0a8-4b8c-ae09-b8a76faaa6f6

**Comment by marklawlor** [comment]
@Viraj-10 I just published `4.1.13` which fixes a related issue for apps using React Navigation (including Expo Router). I'm unable to reproduce the issue in `4.1.13`, can you please try it

**Comment by Viraj-10** [comment]
@marklawlor, I am still getting this error here is [repo](https://github.com/Viraj-10/shadow-nativewind-v4-issue).
Issue occurs on the second render. for first render it works fine.

**Comment by marklawlor** [comment]
@Viraj-10 Try `4.1.14`, that will fix the crash. I'm still looking into some other unusual behaviour that some people are seeing
