### ISSUE TITLE
Styles Broken After Upgrading Nativewind

### ISSUE THREAD

**Issue by dukesx** [nativewind/nativewind#1581]
I recently upgraded to SDK 54 of Expo. I updated native wind from 4.1.23 to 4.2.1 and CSS Interop to its latest version and after that the styles are now broken, nothing gets applied and on debugging, no significant finding, everything works, tailwind works but still nothing. I tried Downgrading and clearing Metro's Cache but now styles are completely gone, nothing is working.

**Comment by RoyRao2333** [comment]
Also getting this. Any solutions yet?

**Comment by RoyRao2333** [comment]
@dukesx 

Solved by upragding `react-native-css-interop` to `0.2.1`

**Comment by dukesx** [comment]
Given up on expo 54. It's a bad upgrade. Tried 0.2.1 CSS Interop and even that didn't fix. Had to rollback commits.

**Comment by RoyRao2333** [comment]
@dukesx 

Sorry to hear that. I'm using bare react-native-cli project and upragding `react-native-css-interop` works for me...

**Comment by dukesx** [comment]
I came from flutter to this, boy, was that a big mistake. People say Vercel and Next JS Suck, wait till you try Expo lol.

**Comment by RoyRao2333** [comment]
@dukesx 

Don't know about Flutter but RN has a larger community and more issues to solve (lol).

Maybe try bare `react-native-cli` if your project is not too big to switch. In that way, you can use any library you want without Expo's limitations.

(Expo can be handy in some out of the box APIs, but pain in the ass in some other scenarios...)
